[program:wgrcfp-queue]
process_name=%(program_name)s_%(process_num)02d
directory=/path/to/women_grc_backend
command=php artisan queue:work redis --sleep=1 --tries=3 --timeout=90 --max-time=3600
autostart=true
autorestart=true
stopwaitsecs=3600
numprocs=4
redirect_stderr=true
stdout_logfile=/var/log/supervisor/wgrcfp-queue.log
