<?php

return [
    'min_chars' => 12,
    'min_words' => 3,
    'banned_words' => [
        'abuse',
        'asshole',
        'bastard',
        'bitch',
        'bloody',
        'bullshit',
        'crap',
        'cunt',
        'damn',
        'dick',
        'fuck',
        'fucker',
        'fucking',
        'idiot',
        'jerk',
        'moron',
        'nude',
        'nudes',
        'porn',
        'pornography',
        'pussy',
        'sex',
        'sexy',
        'shit',
        'slut',
        'stupid',
        'whore',
    ],
];
